name: Testes Automáticos

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Fazer checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Verificar ESLint
      run: npm run lint -- --max-warnings=0
    

    - name: Executar testes
      run: npm test
